### ISSUE TITLE
유저 데이터 조회 후 state값 전달

### ISSUE THREAD

**Issue by iamphj3** [IN-SOPT-WEB/HyeonJiPARK#10]
### 구현하고 싶은 기능
` src/components/SearchInput.tsx `
(1) `getUser` 함수에서 유저 데이터를 불러온 후에, 
(2) `userState`에 현재 상태(waiting,loading,success,fail)와 유저 데이터를 저장하여
(3) '/search/${username}' 에 해당하는 주소로 이동하고,

` src/components/SearchResult/index.tsx`
(4) 위 주소에서 `userState` 를 전달아서
(5) 현재 상태 값에 따라 `UserCard.tsx `, `Loading.tsx `, `NoResult.tsx` 컴포넌트를 보여주고 싶어요!

### 현재 상태
(1) 까지는 정상 작동이 되는데, 불러온 데이터들을
(2) 에서 저장하는 것과 (3)에 넘겨주는 부분이 막혔어요 .... 계속 null로만 넘겨져요 ㅠㅠ

**Comment by Happhee** [comment]
울 공듀 고생해써 체고야💛

**Comment by iamphj3** [comment]
해결!!!!

**1. (2),(3) - 유저 데이터를 저장하여 해당하는 주소로 이동하는 기능**
- 원인 
    - `SearchInput.tsx`의 `getUser` 함수 내부에 navigate로 input에 따라 (3) 주소로 이동하는 코드를 작성하였는데, 
`SearchPage.tsx`에서 `getUser` 함수를 호출한 후에 또 navigate로 input에 해당하는 주소로 이동하게 중복 처리를 해서 계속 null이 넘겨졌었다...!
- 해결 방법 
    - `SearchPage.tsx`에서 navigate로 이동하는 `searchUsers` 함수 삭제!!

**2. (4), (5) - `userState`를 전달받아 상태에 따라 다른 컴포넌트를 보여주는 기능**
- 원인 
    - `userState`가 변경되어도 바로바로 업데이트가 되지 않았기 때문..!!
- 해결 방법 
    - `SearchInput.tsx`에서 useEffect를 통해 `userState`가 업데이트 될 때마다 navigate를 통해 상태에 따라 바로바로 화면이 바뀌게 하였고, 
    - useEffect 내부에서 `getUser`함수의 매개변수인 `username`을 사용하기 위해 useRef에 `usrename`을 저장해 주었다!
    - `index.tsx` 에서 현재 url의 상태 값을 받아오기 위해 useLocation을 사용해주었다
